import { ConnectButton } from "@rainbow-me/rainbowkit";
import { utils } from "ethers";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import {
  useAccount,
  useContractWrite,
  useNetwork,
  usePrepareContractWrite,
} from "wagmi";
import { abi, contractAddress, mintPrice } from "../src/contract";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [amount, setAmount] = useState(1);

  const { address } = useAccount();
  const { chain } = useNetwork();
  const { config } = usePrepareContractWrite({
    address: contractAddress(chain?.name),
    abi,
    functionName: "mint",
    args: [address, amount],
    overrides: {
      value: utils.parseEther(mintPrice(chain?.name)).mul(amount),
    },
  });
  const { isLoading, isSuccess, isError, write } = useContractWrite(config);

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <h1 className={styles.title}>OG Potheads</h1>

        <p className={styles.description}>
          OG Potheads is a community of OG Potheads who are OG Potheads.
          <br />
          Mint one of our OG Pothead NFTs and become an OG Pothead.
        </p>

        <div className={styles.grid}>
          <p>Pick an amount</p>
          <input
            type="number"
            placeholder="5"
            value={amount}
            onChange={(e) => setAmount(Number(e.target.value))}
            min={1}
            max={20}
          />
          <br />
          <button disabled={!write || isLoading} onClick={() => write?.()}>
            Mint
          </button>
          {isLoading && <p>Minting...</p>}
          {isSuccess && <p>Minted!</p>}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="http://ogpothead.com/"
          rel="noopener noreferrer"
          target="_blank"
        >
          By the OG Pothead
        </a>
        |
        <a
          href={`${
            chain?.blockExplorers?.default.url
          }/address/${contractAddress(chain?.name)}`}
          rel="noopener noreferrer"
          target="_blank"
        >
          Etherscan
        </a>
      </footer>
    </div>
  );
};

export default Home;
